### ISSUE TITLE
Ondelete

### ISSUE THREAD

**Issue by ChrisSoper1** [jam941/JamboreeScoreboard#4]
https://github.com/jam941/JamboreeScoreboard/blob/008cdfa4f4e7912721377e556378f7a2ddf1111c/backend/models.py#L39

Does it make sense for this to change to `on_delete=set_null` instead of `on_delete=cascade`? 

Can a patrol be reformed?

**Comment by jam941** [comment]
Yes, makes sense, especially if a patrol has to be reformed because more scouts are there than originally reported or other similar issues
